---
 - name: Creating the Variables 
   hosts: webserver
   gather_facts: false
   vars:
    name: "Pushparaj"
    Company: "Wipro Limited"
    Location: "Chennai"
   tasks:
    - name: Executing the variables
      debug:
       msg: 
        - "My Name is {{name}}"
        - "I am working in {{Company}} company"
        - "My current working location {{Location|type_debug}}"

      